config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper 
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :hotels
      resources :users
      get 'hotels/:id/hotelrooms' ,:to => 'hotels#hotelrooms'
      get 'users/:id/userlogs' ,:to => 'users#userlogs'
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'user/index' ,:to => 'user#index' , as: :user_hotel_index
  get 'user/searchhotel' ,:to => 'user#searchhotel' , as: :search_hotel
  get 'user/:id/show' ,:to => 'user#show' , as: :user_hotel_show
  get 'user/:id/roomlist' ,:to => 'user#roomlist' , as: :user_hotel_roomlist
  get 'user/:id/bookingpage' ,:to => 'user#bookingpage' , as: :user_bookingpage
  post 'user/:id/bookingpage' ,:to => 'user#book' 
  get 'logs' , :to => 'user#showlogs' ,as: :logs
  get 'hotellogs' , :to => 'hotel#hotellogs' ,as: :hotellogs 
  get 'hotels/addaddress' , :to => 'hotel#addaddress' ,as: :hoteladdress
  post 'hotels/addaddress' , :to => 'hotel#add' 
  devise_for :hotels
  get '/rooms/:id/changestatus/' , :to => 'rooms#changestatus' , as: :change_status 
  resources :rooms do
    collection { post :import }
  end
  devise_for :users
  
  # root 'home#index'
  root 'rooms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="footer">
    <div class="container2">
        <div class="cpy">
            <h1>Room Booking</h1>
            <p>Copyright &copy; 2021</p>
        </div>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
        <div class="social">
            <a href="#"><i class="fab fa-github fa-2x"></i></a>
            <a href="#"><i class="fab fa-instagram fa-2x"></i></a>
            <a href="#"><i class="fab fa-twitter fa-2x"></i></a>
            <a href="#"><i class="fab fa-facebook fa-2x"></i></a>
        </div>
        </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-light navbar-expand-lg" style="background-color:rgb(73, 151, 165);">
<span class="material-icons mx-2" style="font-size: 36px;">
hotel
</span>
  <%= link_to "Room Booking" ,root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto my-3">     
       <% if hotel_signed_in? %>
        <li class="nav-item">
          <%= link_to "Rooms" ,rooms_path ,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logs', hotellogs_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Room" ,new_room_path ,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Address" ,hoteladdress_path ,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_hotel_registration_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <strong><%= link_to current_hotel.name ,rooms_path ,class:"nav-link " %></strong>
        </li>
        <li class="nav-item">
           <strong><%= link_to "Sign Out" ,destroy_hotel_session_path,method: :delete ,class:"nav-link" %> </strong>
        </li>
      <% elsif user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Book Room', search_hotel_path , class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Booked Rooms', logs_path , class:"nav-link" %>
          </li>
         <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <strong><%= link_to current_user.name ,root_path ,class:"nav-link " %></strong>
        </li>
           <strong><%= link_to "Sign Out" ,destroy_user_session_path,method: :delete ,class:"nav-link" %> </strong>
        </li>
      <% else %>
        <li class="nav-item mx-4">
          <%= link_to "User SignIn" ,new_user_session_path ,class:"nav-link "  %>
        </li>
        <li class="nav-item mx-4">
          <%= link_to "User SignUp", new_user_registration_path ,class:"nav-link " %>
        </li>
        <li class="nav-item mx-4">
          <%= link_to "Hotel SignIn" ,new_hotel_session_path ,class:"nav-link " %>
        </li>
        <li class="nav-item mx-4">
          <%= link_to "Hotel SignUp", new_hotel_registration_path ,class:"nav-link " %>
        </li>
      <% end %>
    </ul>
    <strong> <%= link_to "Admin", new_admin_user_session_path ,class:"btn btn-outline-dark" %></strong>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Room Booking Application</h1>