config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper 
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :hotels
      resources :users
      get 'hotels/:id/hotelrooms' ,:to => 'hotels#hotelrooms'
      get 'users/:id/userlogs' ,:to => 'users#userlogs'
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'user/index' ,:to => 'user#index' , as: :user_hotel_index
  get 'user/searchhotel' ,:to => 'user#searchhotel' , as: :search_hotel
  get 'user/:id/show' ,:to => 'user#show' , as: :user_hotel_show
  get 'user/:id/roomlist' ,:to => 'user#roomlist' , as: :user_hotel_roomlist
  get 'user/:id/bookingpage' ,:to => 'user#bookingpage' , as: :user_bookingpage
  post 'user/:id/bookingpage' ,:to => 'user#book' 
  get 'logs' , :to => 'user#showlogs' ,as: :logs
  get 'hotellogs' , :to => 'hotel#hotellogs' ,as: :hotellogs 
  get 'hotels/addaddress' , :to => 'hotel#addaddress' ,as: :hoteladdress
  post 'hotels/addaddress' , :to => 'hotel#add' 
  devise_for :hotels
  get '/rooms/:id/changestatus/' , :to => 'rooms#changestatus' , as: :change_status 
  resources :rooms do
    collection { post :import }
  end
  devise_for :users
  
  # root 'home#index'
  root 'rooms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :logs
         has_many :hotels , :through=> :logs
         has_many :access_grants,
           class_name: 'Doorkeeper::AccessGrant',
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
           class_name: 'Doorkeeper::AccessToken',
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks
           
           def self.authenticate(email, password)
            user = User.find_for_authentication(email: email)
            user&.valid_password?(password) ? user : nil
          end

          def active_for_authentication?
            super && !self.ban_status
          end
       
          def inactive_message
            "Your account has been banned"
          end
end

app/controllers/api/v1/users_controller.rb
module Api
    module V1
      class UsersController < ApplicationController
        before_action :doorkeeper_authorize!
        respond_to :json
        protect_from_forgery with: :null_session
        before_action :find_user , only: [:show,:update,:destroy,:userlogs]
        before_action :findEmail , only: [:create]

        def index
          @users = User.all
          render json:@users
        end

        def show 
          if @user
            render json: {user: @user , message: "Successfull"} , status:200
          else
            render json: {error: "No user Found"} , status:400
          end
        end

        def create
          @user = User.new
          @user.email = params[:email]
          @user.password = params[:password]
          @user.name = params[:name]
          @user.phoneno = params[:phoneno]
          @user.address = params[:address]
          if @user.save
            render json:@user
          else
            render error: {error: "Unable to insert"} , status:400
          end
        end

        def update
          if @user
            @user.update(user_params)
            render json: {user:@user , message: "Successfully updated"} , status:200
          else
            render json: {message: "Unable to update"} , status:400
          end
        end

        def destroy
          if @user
            @user.destroy
            render json: {message: "Successfully Deleted"} , status:200
          else
            render json: {message: "Unable to Delete" , error: error} , status:400
          end
        end

        def userlogs
          if @user
            @logs = Log.where(user_id: @user.id)
            render json: {user: @user , logs:@logs , message: "Successfull"} , status:200
          else
            render json: {error: "No User Found"} , status:400
          end
        end

        def find_user
          if User.where(id: params[:id]).empty?
            render json:{message:"User not found"} , status:400
          else
            @user = User.find(params[:id])
          end          
        end

        def findEmail
          @email = User.find_by(email: params[:email])
          if @email
            render json:{message:"Email Id already exixts"} , status:200
          end
        end

        def user_params
          params.require(:user).permit(:email, :password, :name , :phoneno , :address)
        end

      end
    end
  end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def index
    #Using PLUCK
    # @address = Address.where(location: params[:location])
    # @hotel_ids = @address.pluck(:hotel_id)
    # @hotels=Hotel.where(id: @hotel_ids)

    #Using JOINS
    if params[:location] != ""
      @hotels = Hotel.joins(:address).where("addresses.location = ? ", params[:location].capitalize)
    elsif params[:pincode] !=""
      @hotels = Hotel.joins(:pincode).where("pincode= #{params[:pincode]}")
    elsif params[:location] != "" && params[:pincode] !=""
      @hotels = Hotel.joins(:address).where("addresses.location = ? ", params[:location].capitalize)
    else
      redirect_to search_hotel_path, notice: "Enter Pincode or Location to search for Hotels"
    end
    
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def roomlist
    @hotel = Hotel.find(params[:id])
    @rooms = @hotel.rooms.where(status: true)
    @count = @hotel.rooms.where(status: true).count
  end

  def searchhotel
  end

  def bookingpage
    @room = Room.find(params[:id])
  end

  def book 
    @log = current_user.logs.build
    @log.hotel_id= params[:hotel_id]
    @log.room_id= params[:room_id]
    @log.hotel_name= params[:hotel_name]
    @log.start_date= params[:start_date]
    @log.end_date= params[:end_date]
    @log.user_id= params[:user_id]
    @log.room_no= params[:room_no]

      # $rom = Room.find(params[:id])
      respond_to do |format|
        if @log.save
          format.html { redirect_to root_path, notice: "Room was successfully Booked." }
        else
          format.html { redirect_to user_bookingpage_path , notice: "Give a Valid Start Date and End Date " }
        end
    end
    
  end

  def showlogs
    @logs = current_user.logs.all

    @hotels = current_user.hotels.distinct
    @count = @logs.group(:hotel_name).count

    @room_nos = @logs.joins(:hotel).distinct.pluck(:room_no,:hotel_name)
  end

  # def validDate(sdate,edate)
  #   valid = false
  #   if Date.today == Date.parse(sdate) || Date.today < Date.parse(sdate)
  #     valid = true
  #   end
  #   if Date.parse(sdate) < Date.parse(edate) ||  Date.parse(sdate) == Date.parse(edate)
  #     valid = true
  #   else
  #     valid = false
  #   end
  #   return valid
  # end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_form.html.erb
<h4><strong><%= @room.room_no %></strong></h3>
<h4><strong><%= @room.hotel.name %></strong></h4>
<h5>Type : <%= @room.room_type %></h5>
<h5>Price : <%= @room.price %></h5>
<h5>Beds : <%= @room.no_of_beds %></h5>
<hr>

<%= form_with  url: "bookingpage" ,method: :post do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <% log.errors.each do |error| %>
        <div class=" alert alert-danger alert-dismissible fade show" role="alert">
            <%= error.full_message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :hotel_id ,value:@room.hotel_id , class:"form-control" ,type: :hidden%>
  </div>
    <div class="field form-group">
    <%= form.text_field :user_id ,value:current_user.id , class:"form-control" ,type: :hidden %>
  </div>
  <div class="field form-group">
    <%= form.text_field :hotel_name ,value: @room.hotel.name , class:"form-control",type: :hidden%>
  </div>
  <div class="field form-group">
    <%= form.text_field :room_no ,value: @room.room_no , class:"form-control",type: :hidden%>
  </div>
  <div class="field form-group">
    <%= form.text_field :room_id ,value: @room.id , class:"form-control" ,type: :hidden %>
  </div>
  <div class="field form-group">
    <label for="start_date">Start Date</label>
    <%= form.date_field :start_date , class:"form-control" ,id:"start_date",required: true%>
  </div>
  <div class="field form-group">
    <label for="end_date">End Date</label>
    <%= form.date_field :end_date , class:"form-control" ,id:"start_date", required: true%>
  </div>
  <div class="actions">
    <%= form.submit "Book", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/user/bookingpage.html.erb
<%= render 'form', log: Log.new %>
<%= link_to 'Back', search_hotel_path ,class:"btn btn-dark mt-2" %>

app/views/user/index.html.erb
<% if user_signed_in? %>
    <% if !@hotels.empty? %>
        <div class="row m-4">
            <% @hotels.each do |hotel| %>
                <div class="card col-sm-5 m-3" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title"> <i class="fas fa-hotel"></i> <%= hotel.name %></h5>
                        <h6 class="card-subtitle mb-2 text-muted"><i class="fas fa-map-marker-alt"></i> <%= hotel.address.location %></h6>
                        <p class="card-text"><i class="fas fa-phone"></i> <%= hotel.phoneno %> | <i class="fas fa-envelope"></i> <%= hotel.email %></p>
                        <%= link_to "Book Now" , user_hotel_roomlist_path(hotel) ,class:"card-link btn btn-success" %>
                        <%= link_to "View Details" , user_hotel_show_path(hotel), class:" card-link btn btn-primary"%>
                    </div>
                </div>
            <% end %>
        </div>
        <% else %>
        <h3>No hotel found at this location .</h3>
    <% end %>
    <%= link_to 'Back', search_hotel_path ,class:"btn btn-dark" %>
<% else %>
  <h1>Room Booking Application</h1>
<% end %>

app/views/user/roomlist.html.erb
<div class="row">
    <% if @count ==1 %>
        <% @rooms.each do |room| %>
            <div class="card col-sm-5 m-3" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= @hotel.name %></h6>
                    <p class="card-text">Price : <%= room.price %></p>
                    <p class="card-text">Type : <%= room.room_type %></p>
                    <p class="card-text">Beds : <%= room.no_of_beds %> <i class="fas fa-bed"></i></p>
                    <%= link_to 'Book Now', user_bookingpage_path(room) ,class:"btn btn-success" %>
                </div>
            </div>
        <% end %>
    <% elsif @count==0 %>
        <div class="card-body">
            <h3 class="card-title">No rooms available right now.</h3>
        </div>
    <% else %>
        <% @rooms.each do |room| %>
            <div class="card col-sm-5 m-3" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= room.room_no %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= @hotel.name %></h6>
                    <p class="card-text">Price : <%= room.price %></p>
                    <p class="card-text">Type : <%= room.room_type %></p>
                    <p class="card-text">Beds : <%= room.no_of_beds %> <i class="fas fa-bed"></i> </p>
                    <%= link_to 'Book Now', user_bookingpage_path(room) ,class:"btn btn-success" %>
                </div>
            </div>
        <% end %>
    <% end %> 
</div>
<%= link_to 'Back', search_hotel_path ,class:"btn btn-dark mt-2" %>

app/views/user/searchhotel.html.erb
 <form action="/user/index">
  <div class="form-group">
    <label for="location">Location</label>
    <input type="text" class="form-control" id="location" aria-describedby="locationhelp" placeholder="Enter location" name="location" >
  </div>
  <div class="form-group">
    <label for="pincode">Pincode</label>
    <input type="number" class="form-control" id="location" aria-describedby="pincodehelp" placeholder="Enter pincode" name="pincode" >
  </div>
  <button type="submit" class="btn btn-primary">Search Hotels</button>
</form>

app/views/user/show.html.erb
<div class="card">
  <div class="card-header">
     <i class="fas fa-hotel"></i> <%= @hotel.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><i class="fas fa-map-marker-alt"></i> <%= @hotel.address.location %></h5>
    <p class="card-text"><i class="fas fa-phone"></i> Phoneno : <%= @hotel.phoneno %> </p>
    <p class="card-text"><i class="fas fa-envelope"></i> Email : <%= @hotel.email %> </p>
    <p class="card-text">No.of.Rooms : <%= @hotel.room_count %> </p>
    <%= link_to 'Back', search_hotel_path ,class:"btn btn-dark" %>
  </div>
</div>

app/views/user/showlogs.html.erb
<% if user_signed_in? %>

<% if !@hotels.empty? %>
    <div id="accordion">
        <% @hotels.each do |hotel| %>
            <br>
            <div class="card">
                <div class="card-header" id="<%= hotel.name %>">
                <h5 class="mb-0 row">
                    <button class="btn btn-link col-sm-3" data-toggle="collapse" data-target="#<%= hotel.email %>" aria-expanded="true" aria-controls="<%= hotel.email %>">
                        <strong>  <i class="fas fa-hotel"></i> <%= hotel.name %></strong>
                    </button>
                     <div class="col-sm-4"></div>
                    <div class="col-sm-2 btn btn-warning"><%= hotel.address.location %> </div>
                    <div class="col-sm-3">
                        <div class="btn btn-info ">
                            Booked : <span class="badge badge-light"><strong><%= @count[hotel.name] %></strong></span> Times
                        </div>
                    </div>
                </h5>
                </div>
                <div id="<%= hotel.email %>" class="collpse show" aria-labelledby="<%= hotel.name %>" data-parent="#accordion">
                    <div class="card-body">
                        <h5 class="card-title"><strong>Rooms Booked in the past : </h5>
                        <% @room_nos.each do |room_no,hotel_name| %>
                            <% if  hotel_name == hotel.name %>
                                <h6 class="btn btn-info"><strong><%= room_no %></strong></h6> 
                            <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <% else %>
    <h3>No logs.</h3>
<% end %>
<br>
<hr>
<br>
<h2>Complete History</h2>
    <% if !@logs.empty? %>
            <div class="row m-4">
                <% @logs.each do |log| %>
                    <div class="card col-sm-5 m-3" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title"><strong>  <i class="fas fa-hotel"></i> <%= log.hotel_name %></strong></h5>
                            <h6 class="card-subtitle mb-2 text-muted"><strong><%= log.room_no %></strong></h6> 
                            <p class="card-text text-success"><strong> <i class="fas fa-hourglass-start"></i> Start Date :</strong> <%= log.start_date %></p>
                            <p class="card-text text-danger"><strong> <i class="fas fa-hourglass-end"></i> End Date :</strong><%= log.end_date %></p>
                        </div>
                    </div>
                <% end %>
            </div>
            <% else %>
            <h3>No logs.</h3>
        <% end %> 
    <%= link_to 'Back', search_hotel_path ,class:"btn btn-dark" %>
<% else %>
  <h1>Room Booking Application</h1>
<% end %>

app/views/user/showroom.html.erb
<div class="row">
    <% if @count ==1 %>
        <% @rooms.each do |room| %>
            <div class="card col-sm-5 m-3" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= room.room_no %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= @hotel.name %></h6>
                    <p class="card-text">Price : <%= room.price %></p>
                    <p class="card-text">Type : <%= room.room_type %></p>
                    <p class="card-text">Beds : <%= room.no_of_beds %></p>
                    <%= link_to 'Book Now', user_bookingpage_path(room) ,class:"btn btn-success" %>
                </div>
            </div>
        <% end %>
    <% elsif @count==0 %>
        <div class="card-body">
            <h3 class="card-title">No rooms available right now.</h3>
        </div>
    <% else %>
        <% @rooms.each do |room| %>
            <div class="card col-sm-5 m-3" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><%= room.room_no %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= @hotel.name %></h6>
                    <p class="card-text">Price : <%= room.price %></p>
                    <p class="card-text">Type : <%= room.room_type %></p>
                    <p class="card-text">Beds : <%= room.no_of_beds %></p>
                    <%= link_to 'Book Now', user_bookingpage_path(room) ,class:"btn btn-success" %>
                </div>
            </div>
        <% end %>
    <% end %> 
</div>
<%= link_to 'Back', search_hotel_path ,class:"btn btn-dark mt-2" %>