config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper 
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :hotels
      resources :users
      get 'hotels/:id/hotelrooms' ,:to => 'hotels#hotelrooms'
      get 'users/:id/userlogs' ,:to => 'users#userlogs'
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'user/index' ,:to => 'user#index' , as: :user_hotel_index
  get 'user/searchhotel' ,:to => 'user#searchhotel' , as: :search_hotel
  get 'user/:id/show' ,:to => 'user#show' , as: :user_hotel_show
  get 'user/:id/roomlist' ,:to => 'user#roomlist' , as: :user_hotel_roomlist
  get 'user/:id/bookingpage' ,:to => 'user#bookingpage' , as: :user_bookingpage
  post 'user/:id/bookingpage' ,:to => 'user#book' 
  get 'logs' , :to => 'user#showlogs' ,as: :logs
  get 'hotellogs' , :to => 'hotel#hotellogs' ,as: :hotellogs 
  get 'hotels/addaddress' , :to => 'hotel#addaddress' ,as: :hoteladdress
  post 'hotels/addaddress' , :to => 'hotel#add' 
  devise_for :hotels
  get '/rooms/:id/changestatus/' , :to => 'rooms#changestatus' , as: :change_status 
  resources :rooms do
    collection { post :import }
  end
  devise_for :users
  
  # root 'home#index'
  root 'rooms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :hotel
    has_many :logs
    validates :price, presence: true
    validates :room_no , presence: true
    validates :room_no , uniqueness: { scope: :hotel_id , message: " : %{value}  already exists" }
    validates :no_of_beds , presence: {message: " can't be empty"}
    validates :room_type , presence: true

    def self.to_csv
        CSV.generate do |csv|
            csv << column_names
            all.each do |room|
                csv<< room.attributes.values_at(*column_names)
            end
        end
    end

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
          rooms_hash = row.to_hash
          return create(rooms_hash) 
       end
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :authenticate_hotel! , except: [:index]
  before_action :correct_hotel , only: [:show,:edit, :update ,:destroy]

  # GET /rooms or /rooms.json
  def index
    if !current_hotel.nil?
      @rooms = Room.where(hotel_id:current_hotel.id).order("room_no")
      respond_to do |format|
        format.html
        format.csv {send_data @rooms.to_csv}
      end
    end
    if !current_user.nil?
      @near_by_hotels = Hotel.joins(:address).where("addresses.location = ? ",current_user.address)
    end
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    # @room = Room.new
    @room = current_hotel.rooms.build
  end

  # GET /rooms/1/edit
  def edit
  end

  def changestatus
    @room = Room.find(params[:id])
    @stat = !@room.status
    @room.update(status: @stat)
    redirect_to rooms_url
  end
  
  # POST /rooms or /rooms.json
  def create
    # @room = Room.new(room_params)
    @room = current_hotel.rooms.build(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_hotel
    @room = current_hotel.rooms.find_by(id: params[:id])
    redirect_to rooms_path , notice: "Not Authorized" if @room.nil?
  end

  def import
    room = Room.import(params[:file])
    if room.persisted?
      redirect_to root_path, notice: "Rooms imported successfully"
    else
      redirect_to root_path, notice: room.errors.full_messages
    end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:hotel_name, :status, :price, :room_type, :no_of_beds,:hotel_id,:room_no)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <% room.errors.each do |error| %>
        <div class=" alert alert-danger alert-dismissible fade show" role="alert">
            <%= error.full_message %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :room_no %>
    <%= form.text_field :room_no , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :hotel_name , class:"form-control",value:current_hotel.name ,id: :room_hotel_name ,type: :hidden %>
  </div>

  <div class="field form-check">
    <%= form.check_box :status , class:"form-check-input"%>
    <%= form.label "Available" ,class:"form-check-label" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class:"form-control" %>
  </div>

 <%
=begin%>
 <div class="field form-group">
    <%= select_tag(:room_type, options_for_select([["AC","AC"],["No-AC","NONAC"]], params[:type] ), class:"form-control") %>
  </div>   
<%
=end%>

 <div class="field form-group">
     <%= form.label :room_type %>
    <%= form.text_field :room_type, class:"form-control" %>
  </div>  

  <div class="field form-group">
    <%= form.label :no_of_beds %>
    <%= form.number_field :no_of_beds, class:"form-control" %>
  </div>
   <div class="field form-group">
    <%= form.number_field :hotel_id, class:"form-control" , value:current_hotel.id ,id: :room_hotel_id,type: :hidden %>
  </div>
  <%
=begin%>
 <%= current_hotel.inspect %> 
<%
=end%>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/rooms/changestatus.html.erb
<%= params[:id] %>
<%= @room.status %>
<%= @stat %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<br>
<%= link_to 'Show', @room ,class:"btn btn-secondary"%>
<%= link_to 'Back', rooms_path,class:"btn btn-dark" %>

app/views/rooms/index.html.erb
<%
=begin%>
 <p id="notice"><%= notice %></p> 
<%
=end%>
<% if hotel_signed_in? %>
<table class="table table-striped ">
  <thead style="background-color: #e3f2fd;">
    <tr>
      <th>Room Number</th>
      <th>Hotel name</th>
      <th>Available</th>
      <th colspan="1"></th>
      <th>Price</th>
      <th>Type</th>
      <th>No of beds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
      <td><%= room.room_no %></td>
        <td><%= room.hotel_name %></td>
        <td>
          <% if room.status %>
            <i class="fas fa-toggle-on"></i> Yes
          <% else %>
            <i class="fas fa-toggle-off"></i> No
          <% end %>
        </td>
        <td><%= link_to 'Change', change_status_path(room) %></td> 
        <td><%= room.price %></td>
        <td><%= room.room_type %></td>
        <td><%= room.no_of_beds %></td>  
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <div class="row">

  <%= link_to 'New Room', new_room_path,class:"btn btn-secondary col-2 mx-2" %>

  <div class="btn btn-primary col-2">
    <i class="fas fa-file-csv fa-lg"></i>
    <%= link_to 'Download CSV', "/rooms.csv",style:"color:white;text-decoration:none;" %>
  </div> 

  <%= form_tag import_rooms_path, multipart: true,class:"col-7 form-row" do%>
    <div class="custom-file col-7">
      <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
      <%= file_field_tag :file ,required: true , class:"custom-file-input" %>
      <%= submit_tag "Import" ,class:"btn btn-success mt-2 "%>
    </div>
  <% end %>

 </div>

<% elsif user_signed_in?%>
  <h2>Best Hotels at your Location</h2>
  <% if !@near_by_hotels.empty? %>
          <div class="row m-4">
              <% @near_by_hotels.each do |hotel| %>
                  <div class="card col-sm-5 m-3" style="width: 18rem;">
                      <div class="card-body">
                          <h5 class="card-title"><strong> <i class="fas fa-hotel"></i> <%= hotel.name %></strong></h5>
                          <h6 class="card-subtitle mb-2 text-muted"><strong> <i class="fas fa-map-marker-alt"></i> <%= hotel.address.location %></strong></h6> 
                          <p class="card-text"> <span class="material-icons">meeting_room</span> <strong> Room Count :</strong> <%= hotel.room_count %></p>
                          <p class="card-text"> <i class="fas fa-phone"></i> <%= hotel.phoneno %> | <i class="fas fa-envelope"></i> <%= hotel.email %></p>
                          <%= link_to "Book Now" , user_hotel_roomlist_path(hotel) ,class:"card-link btn btn-success" %>
                      </div>
                  </div>
              <% end %>
          </div>
          <% else %>
          <h3>No Hotel Found at your location</h3>
          <%= link_to "Search Hotel" , search_hotel ,class:"card-link btn btn-success" %>
      <% end %> 
  <% else %>
  <h1 style="text-align:center;">Room Booking Application</h1>
  <%= image_tag "room-booking.svg" , class:"svg" %>
<% end %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>
<br>
<%= link_to 'Back', rooms_path ,class:"btn btn-secondary"%>

app/views/rooms/show.html.erb
<div class="card">
  <div class="card-header">
     <i class="fas fa-hotel"></i> <%= @room.room_no %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @room.hotel_name %></h5>
    <p class="card-text">Price : <%= @room.price %> </p>
    <p class="card-text">Status : 
      <% if @room.status %>
            <i class="fas fa-toggle-on"></i> Available
          <% else %>
            <i class="fas fa-toggle-off"></i> Not Available
          <% end %>
    </p>
    <p class="card-text">Type : <%= @room.room_type %> </p>
    <p class="card-text">No.of.Beds : <%= @room.no_of_beds %> <i class="fas fa-bed"></i> </p>
    <%= link_to 'Edit', edit_room_path(@room) ,class:"btn btn-secondary" %>
  <%= link_to 'Back', rooms_path ,class:"btn btn-dark" %>
  </div>
</div>